FootballManager.Web/Models/ErrorViewModel.cs
using System;

namespace FootballManager.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FootballManager.Web/Controllers/ChampionshipCommandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FootballManager.Bl.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace FootballManager.Web.Controllers
{
    public class ChampionshipCommandsController : Controller
    {
        private readonly IChampionshipCommandService _ChampionshipCommandService;
        private readonly IFMService _FMService;

        public ChampionshipCommandsController(IChampionshipCommandService ChampionshipCommandService, IFMService FMService)
        {
            _ChampionshipCommandService = ChampionshipCommandService;
            _FMService = FMService;

        }
        public IActionResult Index(int NumberOfCommands)
        {
            if (NumberOfCommands != 0)
            {
                return View(_FMService.FindChampionshipCommand(NumberOfCommands));
            }

            else
            {
                return View(_ChampionshipCommandService.List());
            }
        }

        public IActionResult Update(int ID)
        {
            return View(_ChampionshipCommandService.Get(ID));
        }

        public IActionResult Create(int ID)
        {
            return View(_ChampionshipCommandService.Get(ID));
        }

        public IActionResult Delete(int ID)
        {
            return View(_ChampionshipCommandService.Get(ID));
        }
    }
}

FootballManager.Web/Controllers/ChampionshipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FootballManager.Bl.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace FootballManager.Web.Controllers
{
    public class ChampionshipsController : Controller
    {
        private readonly IChampionshipService _ChampionshipService;
        private readonly IFMService _FMService;
        public ChampionshipsController(IChampionshipService ChampionshipService, IFMService FMService)
        {
            _ChampionshipService = ChampionshipService;
            _FMService = FMService;
        }

        public IActionResult Index(string Name)
        {

            if (!String.IsNullOrEmpty(Name))
            {
                return View(_ChampionshipService.FindByName(Name));
            }
            else
            {
                return View(_ChampionshipService.List());
            }

        }

        public IActionResult Update(int ID)
        {
            return View(_ChampionshipService.Get(ID));
        }

        public IActionResult Delete(int ID)
        {
            return View(_ChampionshipService.Get(ID));
        }

        public IActionResult Create(int ID)
        {
            return View(_ChampionshipService.Get(ID));
        }
    }
}

FootballManager.Web/Controllers/CommandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FootballManager.Bl.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace FootballManager.Web.Controllers
{
    public class CommandsController : Controller
    {
        private readonly ICommandService _CommandService;
        private readonly IFMService _FMService;
        public CommandsController(ICommandService CommandService, IFMService FMService)
        {
            _CommandService = CommandService;
            _FMService = FMService;
        }

        public IActionResult Index(string Name, string Country)
        {

            if (!String.IsNullOrEmpty(Name) || !String.IsNullOrEmpty(Country))
            {
                return View(_CommandService.FindByName(Name));
            }
            else
            {
                return View(_CommandService.List());
            }

        }

        public IActionResult Update(int CommandID)
        {
            return View(_CommandService.Get(CommandID));
        }

        public IActionResult Delete(int CommandID)
        {
            return View(_CommandService.Get(CommandID));
        }

        public IActionResult Create(int CommandID)
        {
            return View(_CommandService.Get(CommandID));
        }
    }
}

FootballManager.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FootballManager.Bl.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FootballManager.Web.Models;

namespace FootballManager.Web.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

FootballManager.Web/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FootballManager.Bl.Abstract;
using FootballManager.Bl.Impl;
using Microsoft.AspNetCore.Mvc;

namespace FootballManager.Web.Controllers
{
    public class MatchesController : Controller
    {
        private readonly IMatchService _MatchService;
        private readonly IFMService _FMService;
        public MatchesController(IMatchService MatchService, IFMService FMService)
        {
            _MatchService = MatchService;
            _FMService = FMService;
        }

        public IActionResult Index(int Result)
        {
            //return View(_MatchService.FindByResult(Result));
            return View(_MatchService.List());
        }

        public IActionResult Create(int MatchID)
        {
            return View(_MatchService.Get(MatchID));
        }

        public IActionResult Delete(int MatchID)
        {
            return View(_MatchService.Get(MatchID));
        }

        public IActionResult Update(int MatchID)
        {
            return View(_MatchService.Get(MatchID));
        }
    }
}

FootballManager.Web/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using FootballManager.Bl.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace FootballManager.Web.Controllers
{
    public class PlayersController : Controller
    {
        private readonly IPlayerService _PlayerService;
        private readonly IFMService _FMService;
        public PlayersController(IPlayerService PlayerService, IFMService FMService)
        {
            _PlayerService = PlayerService;
            _FMService = FMService;
        }

        public IActionResult Index(string FirstName)
        {

            if (!String.IsNullOrEmpty(FirstName))
            {
                return View(_PlayerService.FindByFirstName(FirstName));
            }
            else
            {
                return View(_PlayerService.List());
            }

        }

        public IActionResult Update(int ID)
        {
            return View(_PlayerService.Get(ID));
        }

        public IActionResult Delete(int ID)
        {
            return View(_PlayerService.Get(ID));
        }

        public IActionResult Create(int ID)
        {
            return View(_PlayerService.Get(ID));
        }
    }
}

FootballManager.Web/Views/ChampionshipCommands/Create.cshtml
@model Models.ChampionshipCommandDTO
@{
    ViewData["Title"] = "Index";
}

<h1>Championship Commands</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ChampionshipID" class="control-label"></label>
                <input asp-for="ChampionshipID" class="form-control" />
                <span asp-validation-for="ChampionshipID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CommandID" class="control-label"></label>
                <input asp-for="CommandID" class="form-control" />
                <span asp-validation-for="CommandID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FootballManager.Web/Views/ChampionshipCommands/Delete.cshtml
@model Models.ChampionshipCommandDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Championship Commands</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CommandID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CommandID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChampionshipID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChampionshipID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ChampionshipCommandID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FootballManager.Web/Views/ChampionshipCommands/Index.cshtml
@model IEnumerable<Models.ChampionshipCommandDTO>
@{
    ViewData["Title"] = "Index";
}

<h1>Championship Commands</h1>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search by Name: <input type="text" name="Name" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Show all</a>
        </p>
    </div>
</form>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search by Commands: <input type="text" name="Commands" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Show all</a>
        </p>
    </div>
</form>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search by Championship: <input type="text" name="Championship" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Show all</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
    <tr>
        <th>CommandID</th>
        <th>ChampionshipID</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.CommandID)</td>
            <td>@Html.DisplayFor(modelItem => item.ChampionshipID)</td>
            <td>
                <a asp-action="Create" asp-route-id="@item.ChampionshipCommandID">Create</a>  |
                <a asp-action="Update" asp-route-id="@item.ChampionshipCommandID">Update</a>  |
                <a asp-action="Delete" asp-route-id="@item.ChampionshipCommandID">Delete</a>
            </td>
        </tr>
    }
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
        </tr>
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Commands)</td>
        </tr>
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Championship)</td>
        </tr>
    }
    </tbody>
</table>

FootballManager.Web/Views/ChampionshipCommands/Update.cshtml
@model Models.ChampionshipCommandDTO

@{
    ViewData["Title"] = "Update";
}
<h1>Championship Commands</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ChampionshipCommandID" />
            <div class="form-group">
                <label asp-for="CommandID" class="control-label"></label>
                <input asp-for="CommandID" class="form-control" />
                <span asp-validation-for="CommandID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampionshipID" class="control-label"></label>
                <input asp-for="ChampionshipID" class="form-control" />
                <span asp-validation-for="ChampionshipID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootballManager.Web/Views/Championships/Create.cshtml
@model Models.ChampionshipDTO
@{
    ViewData["Title"] = "Index";
}

<h1>Championships</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FootballManager.Web/Views/Championships/Delete.cshtml
@model Models.ChampionshipDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Championships</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FootballManager.Web/Views/Championships/Index.cshtml
@model IEnumerable<Models.ChampionshipDTO>
@{
    ViewData["Title"] = "Index";
}

<h1>Commands</h1>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search by Name: <input type="text" name="Name" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Show all</a>
        </p>
    </div>
</form>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search by ID: <input type="text" name="CommandID" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Show all</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>ID</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.ID)</td>
                <td>
                    <a asp-action="Create" asp-route-id="@item.ID">Create</a>  |
                    <a asp-action="Update" asp-route-id="@item.ID">Update</a>  |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.ID)</td>
            </tr>
        }
    </tbody>
</table>

FootballManager.Web/Views/Championships/Update.cshtml
@model Models.ChampionshipDTO

@{
    ViewData["Title"] = "Update";
}
<h1>Championships</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootballManager.Web/Views/Commands/Create.cshtml
@model Models.CommandDTO
@{
    ViewData["Title"] = "Index";
}

<h1>Commands</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CommandID" class="control-label"></label>
                <input asp-for="CommandID" class="form-control" />
                <span asp-validation-for="CommandID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FootballManager.Web/Views/Commands/Delete.cshtml
@model Models.CommandDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Commands</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CommandID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CommandID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="CommandID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FootballManager.Web/Views/Commands/Index.cshtml
@model IEnumerable<Models.CommandDTO>
@{
    ViewData["Title"] = "Index";
}

<h1>Commands</h1>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search by Name: <input type="text" name="Name" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Show all</a>
        </p>
    </div>
</form>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search by Country: <input type="text" name="Country" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Show all</a>
        </p>
    </div>
</form>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search by CommandID: <input type="text" name="CommandID" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Show all</a>
        </p>
    </div>
</form>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search by PlayerID: <input type="text" name="PlayerID" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Show all</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Country</th>
            <th>PlayerID</th>
            <th>CommandID</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.Country)</td>
            <td>@Html.DisplayFor(modelItem => item.PlayerID)</td>
            <td>@Html.DisplayFor(modelItem => item.CommandID)</td>
            <td>
                <a asp-action="Create" asp-route-id="@item.CommandID">Create</a>  |
                <a asp-action="Update" asp-route-id="@item.CommandID">Update</a>  |
                <a asp-action="Delete" asp-route-id="@item.CommandID">Delete</a>
            </td>
        </tr>
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Country)</td>
                <td>@Html.DisplayFor(modelItem => item.PlayerID)</td>
                <td>@Html.DisplayFor(modelItem => item.CommandID)</td>
            </tr>
        }
    </tbody>
</table>

FootballManager.Web/Views/Commands/Update.cshtml
@model Models.CommandDTO

@{
    ViewData["Title"] = "Update";
}
<h1>Commands</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CommandID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootballManager.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to my site!</h1>
    <p>Autor name : Gundarchuk V.M. IT-83</p>
</div>

FootballManager.Web/Views/Matches/Create.cshtml
@model Models.MatchDTO
@{
    ViewData["Title"] = "Index";
}

<h1>Matches</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MatchID" class="control-label"></label>
                <input asp-for="MatchID" class="form-control" />
                <span asp-validation-for="MatchID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Result" class="control-label"></label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FootballManager.Web/Views/Matches/Delete.cshtml
@model Models.MatchDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Matches</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MatchID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MatchID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Result)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Result)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="MatchID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FootballManager.Web/Views/Matches/Update.cshtml
@model Models.MatchDTO

@{
    ViewData["Title"] = "Update";
}
<h1>Matches</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MatchID" />
            <div class="form-group">
                <label asp-for="Result" class="control-label"></label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootballManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FootballManager.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FootballManager.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChampionshipCommands" asp-action="Index">Championship Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Matches" asp-action="Index">Matches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Commands" asp-action="Index">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Championships" asp-action="Index">Championships</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FootballManager.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>